name: Build and Push Docker Image to GitHub Packages

on:
  push:
    branches:
      - main

env:
  DOCKERFILE_PATH: ./server/Dockerfile
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SSL: ${{ secrets.SSL }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Create the SSL file
        run: |
          touch ./server/ssl.crt
          echo "$SSL" >> ./server/ssl.crt

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
